apiVersion : apps/v1
kind: Deployment
metadata:
  name: "couponexchangesystemaks-0c7b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "couponexchangesystemaks-0c7b"
  template:
    metadata:
      labels:
        app: "couponexchangesystemaks-0c7b"
    spec:
      containers:
        - name: "couponexchangesystemaks-0c7b"
          image: "couponexchangesystemregistry.azurecr.io/couponexchangesystemaks"
          ports:
          - containerPort: 80