apiVersion: v1
kind: Service
metadata:
    name: "couponexchangesystemaks-0c7b"
    labels:
        app: "couponexchangesystemaks-0c7b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "couponexchangesystemaks-0c7b"