on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: couponexchangesystemregistry.azurecr.io
        username: ${{ secrets.acr_couponexchangesystemregistry_username }}
        password: ${{ secrets.acr_couponexchangesystemregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CouponExchangeSystemApi_1" -f  "CouponExchangeSystemApi_1/Dockerfile" -t couponexchangesystemregistry.azurecr.io/couponexchangesystemaks:${{ github.sha }} --label dockerfile-path=CouponExchangeSystemApi_1/Dockerfile
        docker push couponexchangesystemregistry.azurecr.io/couponexchangesystemaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_couponexchangesystemaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep couponexchangesystemaks8fb5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace couponexchangesystemaks8fb5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: couponexchangesystemaks8fb5
        container-registry-url: couponexchangesystemregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_couponexchangesystemregistry_username }}
        container-registry-password: ${{ secrets.acr_couponexchangesystemregistry_password }}
        secret-name: couponexchandockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: couponexchangesystemaks8fb5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          couponexchangesystemregistry.azurecr.io/couponexchangesystemaks:${{ github.sha }}
        imagepullsecrets: |
          couponexchandockerauth
